### PR TITLE
Connect Student Profile to backend

### PR DESCRIPTION
**Pull request by NethminiSandunika**
Adds new endpoints for managing student profiles. This include creating, updating, fetching, and deleting profiles in the backend.

### CODE REVIEW

**Comment by NethminiSandunika** [comment]
I have solved the the problem that I faced when storing only the id of actual data by installing Multer middleware.

And created a new directory 'uploads' to save uploaded files.

**Review by RavinduLakshitha — APPROVED** [review]
i fixed some errors. Good work

**Review by Lakshi99 — COMMENTED** [review]
keep it up!

**Review by Lakshi99 — COMMENTED** [review]
keep it up!

**Comment by KushaRa** [comment]
Good job @NethminiSandunika.
I Resolved conflicts within the main branch and feat/StudentProfile

**Pull request merged**
